#include "Vsign_extend.h"   // Verilated header generated by Verilator
#include "verilated.h"
#include <iostream>
#include <cstdint>

int main(int argc, char **argv) {
    Verilated::commandArgs(argc, argv);

    // Instantiate the DUT
    Vsign_extend* dut = new Vsign_extend;

    // Example test vectors
    struct TestCase {
        uint32_t instr;   // 25-bit input (instr[31:7])
        uint8_t ImmSrc;   // 3-bit ImmSrc
        uint32_t expected;
        const char* type;
    };

    TestCase tests[] = {
        {0b1111111111111111111111111, 0b000, 0xFFFFFFFF, "I-type"},  // I-type
        {0b0000000000000000000000001, 0b001, 0x00000081, "S-type"},  // S-type example
        {0b1000000000000000000000000, 0b010, 0xF0000000, "B-type"},  // B-type example
        {0b0111111111111111111111111, 0b011, 0x07FFFFFE, "J-type"},  // J-type example
        {0b0000000000011111111111111, 0b100, 0x0001FFF000, "U-type"} // U-type example
    };

    // Run tests
    for (auto &t : tests) {
        dut->instr = t.instr;
        dut->ImmSrc = t.ImmSrc;

        // Evaluate combinational logic
        dut->eval();

        std::cout << t.type << ": instr=" << std::hex << t.instr
                  << " ImmOp=" << dut->ImmOp
                  << " expected=" << t.expected;

        if (dut->ImmOp == t.expected) std::cout << " ✅";
        else std::cout << " Wrong";

        std::cout << std::endl;
    }

    delete dut;
    return 0;
}
